package pojos;

// Generated Oct 20, 2014 4:49:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Mood generated by hbm2java
 */
public class Mood implements java.io.Serializable {

	private Integer moodId;
	private String moodString;
	private String moodLog;
	private Set<Rate> rates = new HashSet<Rate>(0);

	public Mood() {
	}

	public Mood(String moodString) {
		this.moodString = moodString;
	}

	public Mood(String moodString, String moodLog, Set<Rate> rates) {
		this.moodString = moodString;
		this.moodLog = moodLog;
		this.rates = rates;
	}

	public Integer getMoodId() {
		return this.moodId;
	}

	public void setMoodId(Integer moodId) {
		this.moodId = moodId;
	}

	public String getMoodString() {
		return this.moodString;
	}

	public void setMoodString(String moodString) {
		this.moodString = moodString;
	}

	public String getMoodLog() {
		return this.moodLog;
	}

	public void setMoodLog(String moodLog) {
		this.moodLog = moodLog;
	}

	public Set<Rate> getRates() {
		return this.rates;
	}

	public void setRates(Set<Rate> rates) {
		this.rates = rates;
	}

}
