package pojos;

// Generated Oct 20, 2014 4:49:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Place generated by hbm2java
 */
public class Place implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String pname;
	private String longitude;
	private String latitude;
	private Set<Rate> rates = new HashSet<Rate>(0);

	public Place() {
	}

	public Place(Category category, String pname, String longitude,
			String latitude) {
		this.category = category;
		this.pname = pname;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Place(Category category, String pname, String longitude,
			String latitude, Set<Rate> rates) {
		this.category = category;
		this.pname = pname;
		this.longitude = longitude;
		this.latitude = latitude;
		this.rates = rates;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public Set<Rate> getRates() {
		return this.rates;
	}

	public void setRates(Set<Rate> rates) {
		this.rates = rates;
	}

}
