package pojos;

import java.util.Date;

// Generated Oct 20, 2014 4:49:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rate generated by hbm2java
 */
public class Rate implements java.io.Serializable {

	private Integer rid;
	private User user;
	private Place place;
	private Mood mood;
	private String comment;
	private Date cdate;
	transient private boolean can_edit;
	
	public Rate() {
	}

	public Rate(User user, Place place, Mood mood) {
		this.user = user;
		this.place = place;
		this.mood = mood;
	}

	public Rate(User user, Place place, Mood mood, String comment) {
		this.user = user;
		this.place = place;
		this.mood = mood;
		this.comment = comment;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Place getPlace() {
		return this.place;
	}

	public void setPlace(Place place) {
		this.place = place;
	}

	public Mood getMood() {
		return this.mood;
	}

	public void setMood(Mood mood) {
		this.mood = mood;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCdate() {
		return cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public boolean isCan_edit() {
		return can_edit;
	}

	public void setCan_edit(boolean can_edit) {
		this.can_edit = can_edit;
	}
	
	
	
}
