package pojos;

// Generated Oct 20, 2014 4:49:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String email;
	private String fullName;
	private String picUrl;
	private String accessToken;
	private Set<Rate> rates = new HashSet<Rate>(0);

	public User() {
	}

	public User(String email) {
		this.email = email;
	}

	public User(String email, String fullName, String picUrl,
			String accessToken, Set<Rate> rates) {
		this.email = email;
		this.fullName = fullName;
		this.picUrl = picUrl;
		this.accessToken = accessToken;
		this.rates = rates;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public Set<Rate> getRates() {
		return this.rates;
	}

	public void setRates(Set<Rate> rates) {
		this.rates = rates;
	}

}
